### ISSUE TITLE
Não consigo pushar no master branch

### ISSUE THREAD

**Issue by terciooliveira** [luque-gh/Proto-HKR#4]
Olha a mensagem que dá:

V:\Projects\HK_sandbox\Proto-HKR>git push
remote: Permission to luque-gh/Proto-HKR.git denied to terciooliveira.
fatal: unable to access 'https://github.com/luque-gh/Proto-HKR.git/': The requested URL returned error: 403

**Comment by luque-gh** [comment]
Resolvido ao adicionar devidamente nos colaboradores.
